const ACTION_TYPES = {
    CREATE_HERO: 'CREATE_HERO',
    CREATE_HERO_REQUEST: 'CREATE_HERO_REQUEST',
    CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
    CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',

    CREATE_HEROES: 'CREATE_HEROES',
    CREATE_HEROES_REQUEST: 'CREATE_HEROES_REQUEST',
    CREATE_HEROES_SUCCESS: 'CREATE_HEROES_SUCCESS',
    CREATE_HEROES_ERROR: 'CREATE_HEROES_ERROR',
};
export default ACTION_TYPES;